version: '3'
services:
  nginx:
    image: 192.168.1.23:5000/nginx:1.13
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
    networks:
      - overlay
    deploy:
      replicas: 1

  mysql:
    image: 192.168.1.23:5000/mysql-server:5.7
    environment:
      MYSQL_DATABASE: test
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_HOST: '%'
    ports:
      - "3306:3306"
    volumes:
      - /var/myworkspace/dockercompose-springboot-mysql-nginx/mysql_data/var/lib/mysql:/var/lib/mysql    #To map mysql data path
    networks:
      - overlay
    deploy:
      replicas: 1

  app:
    image: 192.168.1.23:5000/compose_swarm_app:v1.0
    working_dir: /app
    volumes:
      - ./app:/app
      - ~/.m2:/root/.m2
      - /etc:/etc   #To synchronize host localtime and container localtime
    ports:
      - "8088:8088"
    depends_on:
      - nginx
      - mysql
    command: java -jar /root/projects/dockercompose-springboot-mysql-nginx/dockercompose-springboot-mysql-nginx-0.0.1-SNAPSHOT.jar
    networks:
      - overlay
    deploy:
      replicas: 2

networks:
  overlay:

