version: '3'
services:
  nginx02:
    container_name: v-nginx02
    image: 192.168.1.23:5000/nginx:1.13
    restart: always
    hostname: node23
    ports:
      - 81:80
      - 444:443
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
    networks:
      - ingress


  mysql02:
    container_name: v-mysql02
    image: 192.168.1.23:5000/mysql-server:5.7
    environment:
      MYSQL_DATABASE: test02
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_HOST: '%'
    hostname: node31
    ports:
      - "3307:3306"
    volumes:
      - /var/myworkspace/dockercompose-springboot-mysql-nginx/mysql_data/var/lib/mysql:/var/lib/mysql    #To map mysql data path
    restart: always
    networks:
      - ingress

  app02:
    restart: always
    build: ./app
    working_dir: /app
    hostname: node32
    volumes:
      - ./app:/app
      - ~/.m2:/root/.m2
      - /etc:/etc   #To synchronize host localtime and container localtime
    networks:
      - ingress
    expose:
      - "8088"
    depends_on:
      - nginx
      - mysql
    command: mvn clean spring-boot:run -Dspring-boot.run.profiles=docker

  networks:
    ingress:
      driver: overlay